functions:
  knu-speaker-recog:
    runtime: python
    desc: ""
    maintainer: ""
    handler:
      dir: ./src
      file: ""
      name: Handler
    docker_registry: keti.asuscomm.com:5001
    image: keti.asuscomm.com:5001/knu-speaker-recog
    limits:
      memory: ""
      cpu: ""
      gpu: ""
    build_args:
    - CUDA_VERSION=10.0
    - CUDNN_VERSION=7
    - UBUNTU_VERSION=16.04
dcf:
  gateway: keti.asuscomm.com:32222
